import {NextResponse} from 'next/server';
import bcrypt from 'bcryptjs';
import {randomBytes} from 'crypto';
import {getSession} from '../../../../lib/auth';
import {prisma} from '../../../../lib/prisma';
import {writeAudit} from '../../../../lib/audit';

async function ctx(){const s=await getSession();if(!s||s.role!=='ADMIN')return null;const me=await prisma.user.findUnique({where:{id:s.sub},select:{id:true,schoolId:true}});return me?{s,me}:null}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:'Solo administradores'},{status:403});const items=await prisma.integrationSource.findMany({where:{schoolId:c.me.schoolId},include:{syncRuns:{orderBy:{startedAt:'desc'},take:8}},orderBy:{createdAt:'desc'}});return NextResponse.json({items:items.map(x=>({...x,tokenHash:undefined}))})}
export async function POST(req){const c=await ctx();if(!c)return NextResponse.json({error:'Solo administradores'},{status:403});const b=await req.json();if(!b.name?.trim())return NextResponse.json({error:'Indica un nombre para la integración.'},{status:400});const type=['API','CSV','SQLSERVER','MYSQL','POSTGRESQL','SIS'].includes(String(b.type||'').toUpperCase())?String(b.type).toUpperCase():'API';const token=`anova_${randomBytes(24).toString('hex')}`;try{const item=await prisma.integrationSource.create({data:{schoolId:c.me.schoolId,name:b.name.trim(),type,status:'ACTIVE',baseUrl:b.baseUrl?.trim()||null,configJson:b.configJson?JSON.stringify(b.configJson):null,tokenHash:await bcrypt.hash(token,12),tokenPrefix:token.slice(0,12)}});await writeAudit({schoolId:c.me.schoolId,actorId:c.me.id,action:'CREATE',entity:'IntegrationSource',entityId:item.id,summary:`Creó la integración ${item.name}`,details:{type:item.type},request:req});return NextResponse.json({ok:true,item:{...item,tokenHash:undefined},token,message:'Guarda este token ahora: sólo se mostrará una vez.'},{status:201})}catch{return NextResponse.json({error:'No se pudo crear. Verifica que el nombre no esté repetido.'},{status:400})}}
export async function PATCH(req){const c=await ctx();if(!c)return NextResponse.json({error:'Solo administradores'},{status:403});const b=await req.json();const item=await prisma.integrationSource.findFirst({where:{id:b.id,schoolId:c.me.schoolId}});if(!item)return NextResponse.json({error:'Integración no encontrada'},{status:404});if(b.action==='REGENERATE_TOKEN'){const token=`anova_${randomBytes(24).toString('hex')}`;await prisma.integrationSource.update({where:{id:item.id},data:{tokenHash:await bcrypt.hash(token,12),tokenPrefix:token.slice(0,12)}});await writeAudit({schoolId:c.me.schoolId,actorId:c.me.id,action:'ROTATE_TOKEN',entity:'IntegrationSource',entityId:item.id,summary:`Rotó el token de ${item.name}`,request:req});return NextResponse.json({ok:true,token,message:'Guarda este token ahora: sólo se mostrará una vez.'})}const status=b.status==='INACTIVE'?'INACTIVE':'ACTIVE';await prisma.integrationSource.update({where:{id:item.id},data:{status}});await writeAudit({schoolId:c.me.schoolId,actorId:c.me.id,action:'UPDATE',entity:'IntegrationSource',entityId:item.id,summary:`Cambió ${item.name} a ${status}`,request:req});return NextResponse.json({ok:true})}
