'use client';
import {useEffect,useState} from 'react';

const roles={
 Alumno:{initials:'AM',name:'André Moreno',subtitle:'3° A · Bachillerato',menu:['Inicio','Mis materias','Calificaciones','Tareas','Horario','Reportes','Perfil']},
 Profesor:{initials:'ER',name:'Edgar Ramírez',subtitle:'Profesor · Matemáticas',menu:['Inicio','Mis grupos','Materias','Calificaciones','Asistencia','Tareas','Reportes']},
 Administrador:{initials:'AD',name:'Administración',subtitle:'Control escolar',menu:['Inicio','Usuarios','Grupos','Materias','Ciclos escolares','Asignaciones','Auditoría']}
};
const Icon=({name})=><span className="navIcon">{{Inicio:'⌂','Mis materias':'▤','Mis grupos':'◫',Materias:'▤',Calificaciones:'◒',Tareas:'✓',Horario:'◷',Reportes:'!',Perfil:'○',Asistencia:'◎',Usuarios:'♙',Grupos:'◫','Ciclos escolares':'◇',Asignaciones:'↗','Auditoría':'≡'}[name]||'•'}</span>;

function StudentHome({data}){return <><section className="hero"><div><span className="eyebrow">JUEVES · 1 OCTUBRE</span><h1>Buenos días, {data?.user?.firstName||'André'}.</h1><p>Aquí tienes el panorama de tu día académico.</p></div><div className="pulse"><span>ACADEMIC PULSE</span><strong>89</strong><small>Excelente ritmo <b>↗</b></small></div></section><div className="metricGrid"><article><span>Promedio general</span><strong>8.7</strong><small className="up">↑ 0.3 este periodo</small></article><article><span>Asistencia</span><strong>96%</strong><small>2 faltas este ciclo</small></article><article><span>Tareas pendientes</span><strong>3</strong><small>1 vence mañana</small></article><article><span>Próximo examen</span><strong className="smallStrong">Matemáticas</strong><small>Mañana · 10:20</small></article></div><div className="twoCols"><section className="box"><div className="boxHead"><div><span className="eyebrow">HOY</span><h2>Próximas clases</h2></div><button>Ver horario →</button></div><div className="classRow"><time>12:40</time><i></i><div><b>Física</b><span>Laboratorio 2 · Mtro. Salazar</span></div><em>En 52 min</em></div><div className="classRow"><time>14:10</time><i></i><div><b>Literatura</b><span>Aula 304 · Mtra. Rayo</span></div><em>Después</em></div></section><section className="box"><span className="eyebrow">PRIORIDAD A-NOVA</span><h2>Enfócate en Matemáticas</h2><p>Tu examen es mañana y esta materia representa tu oportunidad más cercana de mejorar el promedio.</p><div className="progress"><span style={{width:'78%'}}></span></div><small>Preparación estimada · 78%</small></section></div></>}
function Generic({role,page,data}){if(role==='Alumno'&&page==='Mis materias')return <><section className="hero simple"><div><span className="eyebrow">{data?.cycle||'CICLO ACTIVO'} · {data?.group||''}</span><h1>Mis materias</h1><p>Materias y profesores obtenidos de tu inscripción activa.</p></div></section><section className="box"><div className="chips">{(data?.subjects||[]).map(s=><span key={s.id}><b>{s.name}</b> · {s.teacher}</span>)}</div></section></>;return <><section className="hero simple"><div><span className="eyebrow">A-NOVA · {role.toUpperCase()}</span><h1>{page}</h1><p>Vista de demostración de este módulo.</p></div></section><section className="box empty"><div className="emptyIcon">A</div><h2>{page}</h2><p>Este módulo ya forma parte de la navegación de A-NOVA. Sus funciones y datos reales se conectarán en las siguientes fases.</p><span className="tag">Fase 1.3 · Maqueta</span></section></>}
function ProfessorHome({data}){return <><section className="hero"><div><span className="eyebrow">JUEVES · 1 OCTUBRE</span><h1>Buenos días, {data?.user?.firstName||'Profesor'}.</h1><p>Tus grupos y actividad académica de hoy.</p></div><div className="pulse"><span>GRUPOS ACTIVOS</span><strong>4</strong><small>112 alumnos</small></div></section><div className="metricGrid"><article><span>Clases hoy</span><strong>5</strong><small>Próxima · 12:40</small></article><article><span>Por calificar</span><strong>18</strong><small>Actividades pendientes</small></article><article><span>Asistencia media</span><strong>94%</strong><small>Últimos 30 días</small></article><article><span>Alertas académicas</span><strong>4</strong><small>Requieren revisión</small></article></div><section className="box"><span className="eyebrow">SIGUIENTE CLASE</span><h2>Matemáticas · 3° A</h2><p>32 alumnos · Aula 201 · 12:40–13:30</p><div className="chips"><span>Pasar lista</span><span>Capturar calificaciones</span><span>Ver grupo</span></div></section></>}
function AdminHome({data}){return <><section className="hero"><div><span className="eyebrow">CONTROL ESCOLAR</span><h1>Panel administrativo.</h1><p>Estado general de A-NOVA School.</p></div><div className="pulse"><span>CICLO ACTIVO</span><strong className="year">26<br/>27</strong><small>2026–2027</small></div></section><div className="metricGrid"><article><span>Alumnos</span><strong>{data?.stats?.students??0}</strong><small>{data?.stats?.groups??0} grupos activos</small></article><article><span>Profesores</span><strong>{data?.stats?.teachers??0}</strong><small>Docentes activos</small></article><article><span>Materias</span><strong>{data?.stats?.subjects??0}</strong><small>Plan académico</small></article><article><span>Usuarios activos</span><strong>{(data?.stats?.students??0)+(data?.stats?.teachers??0)+1}</strong><small>Usuarios principales</small></article></div><section className="box"><span className="eyebrow">ACCESOS RÁPIDOS</span><h2>Gestión escolar</h2><div className="chips"><span>+ Nuevo usuario</span><span>Crear grupo</span><span>Nueva materia</span><span>Asignar profesor</span></div></section></>}


function AdminModule({page,onChanged}){const [data,setData]=useState(null),[msg,setMsg]=useState(''),[form,setForm]=useState({role:'STUDENT',active:false});async function load(){const r=await fetch('/api/admin/data');if(r.ok)setData(await r.json())}useEffect(()=>{load()},[page]);async function send(url,body,method='POST'){setMsg('Guardando…');const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setMsg(r.ok?'✓ Cambios guardados':j.error||'Ocurrió un error');if(r.ok){setForm({role:'STUDENT',active:false});await load();onChanged?.()}}if(!data)return <section className="box"><p>Cargando gestión escolar…</p></section>;
 const teachers=data.users.filter(x=>x.role==='TEACHER'&&x.status==='ACTIVE');
 if(page==='Usuarios')return <><section className="hero simple"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Usuarios</h1><p>Alta y control de alumnos, profesores y administradores.</p></div></section><section className="box"><h2>Nuevo usuario</h2><div className="adminForm"><input placeholder="Nombre" value={form.firstName||''} onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Apellidos" value={form.lastName||''} onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="Correo institucional" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="STUDENT">Alumno</option><option value="TEACHER">Profesor</option><option value="ADMIN">Administrador</option></select><input placeholder="Matrícula / No. empleado" value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/>{form.role==='STUDENT'&&<select value={form.groupId||''} onChange={e=>setForm({...form,groupId:e.target.value})}><option value="">Sin grupo por ahora</option>{data.groups.map(g=><option key={g.id} value={g.id}>{g.grade}° {g.name} · {g.cycle.name}</option>)}</select>}<button onClick={()=>send('/api/admin/users',form)}>+ Crear usuario</button></div>{msg&&<p className="adminMsg">{msg}</p>}<div className="adminTable">{data.users.map(u=><div className="adminRow" key={u.id}><div><b>{u.firstName} {u.lastName}</b><span>{u.email} · {u.role}</span></div><button onClick={()=>send('/api/admin/users',{id:u.id,status:u.status==='ACTIVE'?'INACTIVE':'ACTIVE'},'PATCH')}>{u.status==='ACTIVE'?'Desactivar':'Activar'}</button></div>)}</div></section></>;
 if(page==='Materias')return <><section className="hero simple"><div><span className="eyebrow">PLAN ACADÉMICO</span><h1>Materias</h1><p>Crea y administra el catálogo académico.</p></div></section><section className="box"><div className="adminForm"><input placeholder="Código (MAT)" value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/><input placeholder="Nombre de la materia" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/><button onClick={()=>send('/api/admin/subjects',form)}>+ Nueva materia</button></div>{msg&&<p className="adminMsg">{msg}</p>}<div className="adminTable">{data.subjects.map(x=><div className="adminRow" key={x.id}><div><b>{x.name}</b><span>{x.code}</span></div><button onClick={()=>send('/api/admin/subjects',{id:x.id,active:!x.active},'PATCH')}>{x.active?'Desactivar':'Activar'}</button></div>)}</div></section></>;
 if(page==='Ciclos escolares')return <><section className="hero simple"><div><span className="eyebrow">CONFIGURACIÓN</span><h1>Ciclos escolares</h1><p>Define los periodos de operación de la escuela.</p></div></section><section className="box"><div className="adminForm"><input placeholder="2027–2028" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/><input type="date" value={form.startDate||''} onChange={e=>setForm({...form,startDate:e.target.value})}/><input type="date" value={form.endDate||''} onChange={e=>setForm({...form,endDate:e.target.value})}/><label className="check"><input type="checkbox" checked={!!form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Ciclo activo</label><button onClick={()=>send('/api/admin/cycles',form)}>+ Crear ciclo</button></div>{msg&&<p className="adminMsg">{msg}</p>}<div className="adminTable">{data.cycles.map(x=><div className="adminRow" key={x.id}><div><b>{x.name}</b><span>{x.active?'ACTIVO':'Inactivo'}</span></div></div>)}</div></section></>;
 if(page==='Grupos')return <><section className="hero simple"><div><span className="eyebrow">CONTROL ESCOLAR</span><h1>Grupos</h1><p>Organiza alumnos por grado, grupo y ciclo.</p></div></section><section className="box"><div className="adminForm"><select value={form.cycleId||''} onChange={e=>setForm({...form,cycleId:e.target.value})}><option value="">Selecciona ciclo</option>{data.cycles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input type="number" min="1" placeholder="Grado" value={form.grade||''} onChange={e=>setForm({...form,grade:e.target.value})}/><input placeholder="Grupo (A)" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Salón" value={form.room||''} onChange={e=>setForm({...form,room:e.target.value})}/><button onClick={()=>send('/api/admin/groups',form)}>+ Crear grupo</button></div>{msg&&<p className="adminMsg">{msg}</p>}<div className="adminTable">{data.groups.map(g=><div className="adminRow" key={g.id}><div><b>{g.grade}° {g.name}</b><span>{g.cycle.name} · {g.room||'Sin salón'} · {g._count.enrollments} alumnos</span></div></div>)}</div></section></>;
 if(page==='Asignaciones')return <><section className="hero simple"><div><span className="eyebrow">DOCENCIA</span><h1>Asignaciones</h1><p>Vincula profesor, materia y grupo.</p></div></section><section className="box"><div className="adminForm"><select value={form.teacherId||''} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Profesor</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.firstName} {x.lastName}</option>)}</select><select value={form.subjectId||''} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Materia</option>{data.subjects.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={form.groupId||''} onChange={e=>setForm({...form,groupId:e.target.value})}><option value="">Grupo</option>{data.groups.filter(x=>x.active).map(g=><option key={g.id} value={g.id}>{g.grade}° {g.name} · {g.cycle.name}</option>)}</select><button onClick={()=>send('/api/admin/assignments',form)}>+ Asignar</button></div>{msg&&<p className="adminMsg">{msg}</p>}<div className="adminTable">{data.assignments.map(x=><div className="adminRow" key={x.id}><div><b>{x.subject.name} · {x.group.grade}° {x.group.name}</b><span>{x.teacher.firstName} {x.teacher.lastName} · {x.group.cycle.name}</span></div></div>)}</div></section></>;
 return <Generic role="Administrador" page={page}/>}

export default function Home(){const [role,setRole]=useState(null);const [page,setPage]=useState('Inicio');const [refreshKey,setRefreshKey]=useState(0);const [academic,setAcademic]=useState(null);const [checking,setChecking]=useState(true);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const roleMap={STUDENT:'Alumno',TEACHER:'Profesor',ADMIN:'Administrador'};
 async function loadAcademic(){const r=await fetch('/api/academic/dashboard');if(r.ok)setAcademic(await r.json())}
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/auth/me');if(r.ok){const j=await r.json();setRole(roleMap[j.user.role]);await loadAcademic()}}finally{setChecking(false)}})()},[]);
 async function login(e){e.preventDefault();setLoading(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo iniciar sesión.');setRole(roleMap[j.user.role]);setPage('Inicio');await loadAcademic()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setAcademic(null);setRole(null);setEmail('');setPassword('');setPage('Inicio')}
 if(checking)return <main className="login"><section className="brand"><div className="brandMark"><span>A</span></div><div className="wordmark">A-NOVA<small>SCHOOL</small></div></section><section className="loginSide"><div className="loginCard"><span className="eyebrow">A-NOVA</span><h2>Preparando tu sesión…</h2></div></section></main>;
 if(!role)return <main className="login"><section className="brand"><div className="brandMark"><span>A</span></div><div className="wordmark">A-NOVA<small>SCHOOL</small></div><div className="brandCopy"><span className="eyebrow">SMART SCHOOL PLATFORM</span><h1>El futuro académico,<br/>en un solo lugar.</h1><p>Información clara. Decisiones inteligentes. Una nueva forma de vivir la escuela.</p></div><footer>© 2026 A-NOVA · Version 0.1.7</footer></section><section className="loginSide"><form className="loginCard" onSubmit={login}><span className="eyebrow">BIENVENIDO A A-NOVA</span><h2>Inicia sesión</h2><p>Ingresa con tu cuenta institucional.</p><label>Correo institucional</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@anova.edu.mx" autoComplete="email" required/><label>Contraseña</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="••••••••" autoComplete="current-password" required minLength={8}/>{error&&<p style={{color:'#ff8b8b',marginTop:12}}>{error}</p>}<button type="submit" disabled={loading||!email||password.length<8} style={{width:'100%',marginTop:18,padding:'14px 18px',borderRadius:12,border:0,fontWeight:700,cursor:'pointer'}}>{loading?'Verificando…':'Entrar a A-NOVA →'}</button><div className="demoLabel">CUENTAS DE PRUEBA</div><div style={{fontSize:12,lineHeight:1.8,opacity:.75}}>andre@anova.edu.mx · Alumno<br/>edgar@anova.edu.mx · Profesor<br/>admin@anova.edu.mx · Administrador<br/><b>Contraseña: Nova2026!</b></div><div className="secure">◈ &nbsp; Sesión protegida · MVP 1.7</div></form></section></main>;
 const d=roles[role];let body=page==='Inicio'?(role==='Alumno'?<StudentHome data={academic}/>:role==='Profesor'?<ProfessorHome data={academic}/>:<AdminHome data={academic}/>):role==='Administrador'?<AdminModule key={page+refreshKey} page={page} onChanged={()=>{loadAcademic();setRefreshKey(x=>x+1)}}/>:<Generic role={role} page={page} data={academic}/>;
 return <main className="app"><aside><div className="sideBrand"><div className="miniLogo">A</div><div><b>A-NOVA</b><span>SCHOOL</span></div></div><div className="cycle"><span>CICLO ESCOLAR</span><b>2026 — 2027</b></div><nav>{d.menu.map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)} key={x}><Icon name={x}/>{x}</button>)}</nav><div className="userBox"><div className="avatar">{d.initials}</div><div><b>{d.name}</b><span>{d.subtitle}</span></div><button onClick={logout}>↪</button></div></aside><section className="content"><div className="topbar"><span>{page}</span><div><button>⌕</button><button>♢<i></i></button></div></div>{body}<footer className="appFoot">A-NOVA SCHOOL · VERSION 0.1.7</footer></section></main>}
