import {NextResponse} from 'next/server';
import {getSession} from '../../../../lib/auth';
import {prisma} from '../../../../lib/prisma';
import {normalizeBranding} from '../../../../lib/branding';
import {writeAudit} from '../../../../lib/audit';

async function ctx(){const s=await getSession();if(!s||s.role!=='ADMIN')return null;const me=await prisma.user.findUnique({where:{id:s.sub},select:{id:true,schoolId:true,school:{include:{settings:true}}}});return me?{s,me}:null}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:'Solo administradores'},{status:403});return NextResponse.json({branding:normalizeBranding(c.me.school,c.me.school.settings),school:{id:c.me.school.id,name:c.me.school.name,code:c.me.school.code}})}
export async function PUT(req){const c=await ctx();if(!c)return NextResponse.json({error:'Solo administradores'},{status:403});const b=await req.json();const color=x=>/^#[0-9a-fA-F]{6}$/.test(x||'')?x:undefined;const data={displayName:b.displayName?.trim()||null,shortName:b.shortName?.trim()||null,logoUrl:b.logoUrl?.trim()||null,primaryColor:color(b.primaryColor)||'#3155E7',secondaryColor:color(b.secondaryColor)||'#0B1422',accentColor:color(b.accentColor)||'#8093FF',contactEmail:b.contactEmail?.trim()||null,phone:b.phone?.trim()||null,website:b.website?.trim()||null,address:b.address?.trim()||null,city:b.city?.trim()||null,state:b.state?.trim()||null,country:b.country?.trim()||'México',postalCode:b.postalCode?.trim()||null,timezone:b.timezone?.trim()||'America/Mexico_City',locale:b.locale?.trim()||'es-MX',reportFooter:b.reportFooter?.trim()||null,showPoweredBy:b.showPoweredBy!==false};const settings=await prisma.schoolSettings.upsert({where:{schoolId:c.me.schoolId},update:data,create:{schoolId:c.me.schoolId,...data}});if(b.schoolName?.trim())await prisma.school.update({where:{id:c.me.schoolId},data:{name:b.schoolName.trim()}});await writeAudit({schoolId:c.me.schoolId,actorId:c.me.id,action:'UPDATE',entity:'SchoolSettings',entityId:settings.id,summary:'Actualizó la configuración institucional y marca',details:{displayName:data.displayName,shortName:data.shortName},request:req});const school=await prisma.school.findUnique({where:{id:c.me.schoolId},include:{settings:true}});return NextResponse.json({ok:true,branding:normalizeBranding(school,school.settings)})}
