import {NextResponse} from 'next/server';
import bcrypt from 'bcryptjs';
import {randomBytes} from 'crypto';
import {prisma} from '../../../../lib/prisma';
import {writeAudit} from '../../../../lib/audit';

function bearer(req){const h=req.headers.get('authorization')||'';return h.toLowerCase().startsWith('bearer ')?h.slice(7).trim():''}
export async function POST(req){
  const token=bearer(req);if(!token||!token.startsWith('anova_'))return NextResponse.json({error:'Token de integración requerido.'},{status:401});
  const prefix=token.slice(0,12);const candidates=await prisma.integrationSource.findMany({where:{tokenPrefix:prefix,status:'ACTIVE'}});let source=null;for(const x of candidates){if(x.tokenHash&&await bcrypt.compare(token,x.tokenHash)){source=x;break}}
  if(!source)return NextResponse.json({error:'Token inválido o integración inactiva.'},{status:401});
  let body;try{body=await req.json()}catch{return NextResponse.json({error:'JSON inválido.'},{status:400})}
  const rows=Array.isArray(body?.students)?body.students:[];if(!rows.length)return NextResponse.json({error:'Envía students[] con los alumnos a sincronizar.'},{status:400});if(rows.length>2000)return NextResponse.json({error:'Máximo 2000 alumnos por sincronización.'},{status:413});
  const run=await prisma.syncRun.create({data:{integrationId:source.id,status:'RUNNING',received:rows.length}});let created=0,updated=0,skipped=0,failed=0;const errors=[];
  const subscription=await prisma.schoolSubscription.findUnique({where:{schoolId:source.schoolId}});let availableSlots=Infinity;if(subscription){const currentStudents=await prisma.user.count({where:{schoolId:source.schoolId,role:'STUDENT',status:'ACTIVE'}});availableSlots=Math.max(0,subscription.maxStudents-currentStudents)}
  const cycle=await prisma.schoolCycle.findFirst({where:{schoolId:source.schoolId,active:true},orderBy:{startDate:'desc'}});
  for(const row of rows){try{const firstName=String(row.firstName||'').trim(),lastName=String(row.lastName||'').trim(),email=String(row.email||'').trim().toLowerCase(),studentCode=String(row.studentCode||'').trim()||null;if(!firstName||!lastName||!email||!email.includes('@')){skipped++;continue}let existing=await prisma.user.findUnique({where:{email}});if(existing&&existing.schoolId!==source.schoolId){failed++;errors.push(`${email}: pertenece a otro tenant`);continue}if(existing){await prisma.user.update({where:{id:existing.id},data:{firstName,lastName,studentCode:studentCode||existing.studentCode,status:'ACTIVE',role:'STUDENT'}});updated++}else{if(availableSlots<=0){failed++;errors.push(`${email}: límite de alumnos alcanzado`);continue}const randomPassword=randomBytes(24).toString('base64url')+'!A1';existing=await prisma.user.create({data:{schoolId:source.schoolId,firstName,lastName,email,studentCode,role:'STUDENT',status:'ACTIVE',passwordHash:await bcrypt.hash(randomPassword,12),mustChangePassword:true}});created++;if(Number.isFinite(availableSlots))availableSlots--}if(cycle&&row.grade&&row.group){const group=await prisma.group.findFirst({where:{schoolId:source.schoolId,cycleId:cycle.id,grade:Number(row.grade),name:String(row.group).trim(),active:true}});if(group){await prisma.enrollment.updateMany({where:{studentId:existing.id,status:'ACTIVE',groupId:{not:group.id}},data:{status:'WITHDRAWN'}});await prisma.enrollment.upsert({where:{studentId_groupId:{studentId:existing.id,groupId:group.id}},update:{status:'ACTIVE'},create:{studentId:existing.id,groupId:group.id,status:'ACTIVE'}})}}}catch(e){failed++;if(errors.length<20)errors.push(String(e?.message||e).slice(0,160))}}
  const status=failed?'PARTIAL':'SUCCESS';await prisma.syncRun.update({where:{id:run.id},data:{status,created,updated,skipped,failed,summary:errors.length?JSON.stringify(errors):null,completedAt:new Date()}});await prisma.integrationSource.update({where:{id:source.id},data:{lastSyncAt:new Date(),lastError:failed?`${failed} registro(s) con error`:null}});await writeAudit({schoolId:source.schoolId,action:'SYNC',entity:'IntegrationSource',entityId:source.id,summary:`Sincronización ${source.name}: ${created} creados, ${updated} actualizados`,details:{received:rows.length,created,updated,skipped,failed},request:req});return NextResponse.json({ok:true,status,received:rows.length,created,updated,skipped,failed,errors})
}
