import {NextResponse} from 'next/server';
import {getSession} from '../../../lib/auth';import {prisma} from '../../../lib/prisma';import {writeAudit} from '../../../lib/audit';
async function context(){const s=await getSession();if(!s)return null;const user=await prisma.user.findUnique({where:{id:s.sub}});return user?{s,user}:null}
export async function GET(req){const c=await context();if(!c)return NextResponse.json({error:'No autorizado'},{status:401});const {user}=c;const url=new URL(req.url);const studentId=url.searchParams.get('studentId');let groupIds=[];
 if(user.role==='STUDENT'){const es=await prisma.enrollment.findMany({where:{studentId:user.id,status:'ACTIVE'},select:{groupId:true}});groupIds=es.map(x=>x.groupId)}
 else if(user.role==='TUTOR'){if(!studentId)return NextResponse.json({error:'Selecciona un alumno vinculado'},{status:400});const link=await prisma.guardianStudent.findUnique({where:{guardianId_studentId:{guardianId:user.id,studentId}}});if(!link)return NextResponse.json({error:'Alumno no autorizado'},{status:403});const es=await prisma.enrollment.findMany({where:{studentId,status:'ACTIVE'},select:{groupId:true}});groupIds=es.map(x=>x.groupId)}
 else if(user.role==='TEACHER'){const a=await prisma.teachingAssignment.findMany({where:{teacherId:user.id},select:{groupId:true}});groupIds=[...new Set(a.map(x=>x.groupId))]}
 const audience=user.role==='ADMIN'?undefined:user.role;
 const events=await prisma.calendarEvent.findMany({where:{schoolId:user.schoolId,active:true,...(user.role==='ADMIN'?{}:{AND:[{OR:[{audience:'ALL'},{audience}]},{OR:[{groupId:null},...(groupIds.length?[{groupId:{in:groupIds}}]:[])]}]})},orderBy:{startAt:'asc'}});
 let tasks=[];if(user.role==='STUDENT'||user.role==='TUTOR'){const sid=user.role==='STUDENT'?user.id:studentId;tasks=await prisma.academicTask.findMany({where:{active:true,teachingAssignment:{groupId:{in:groupIds}}},include:{teachingAssignment:{include:{subject:true}}},orderBy:{dueDate:'asc'}})}else if(user.role==='TEACHER'){tasks=await prisma.academicTask.findMany({where:{active:true,teachingAssignment:{teacherId:user.id}},include:{teachingAssignment:{include:{subject:true}}},orderBy:{dueDate:'asc'}})}
 const periods=groupIds.length?await prisma.evaluationPeriod.findMany({where:{cycle:{groups:{some:{id:{in:groupIds}}}}},orderBy:{startDate:'asc'}}):[];
 const items=[...events.map(e=>({...e,source:'EVENT'})),...tasks.map(t=>({id:`task-${t.id}`,title:t.title,description:t.teachingAssignment.subject.name,type:'TASK',startAt:t.dueDate,endAt:null,source:'TASK'})),...periods.flatMap(p=>[{id:`period-start-${p.id}`,title:`Inicio · ${p.name}`,type:'PERIOD',startAt:p.startDate,source:'PERIOD'},{id:`period-end-${p.id}`,title:`Cierre · ${p.name}`,type:'PERIOD',startAt:p.endDate,source:'PERIOD'}])].sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));return NextResponse.json({items})}
export async function POST(req){const c=await context();if(!c||c.user.role!=='ADMIN')return NextResponse.json({error:'Solo administradores'},{status:403});const b=await req.json();if(!b.title||!b.startAt)return NextResponse.json({error:'Título y fecha son obligatorios'},{status:400});const e=await prisma.calendarEvent.create({data:{schoolId:c.user.schoolId,title:b.title.trim(),description:b.description?.trim()||null,type:b.type||'SCHOOL',startAt:new Date(b.startAt),endAt:b.endAt?new Date(b.endAt):null,audience:b.audience||'ALL',groupId:b.groupId||null,createdById:c.user.id}});await writeAudit({schoolId:c.user.schoolId,actorId:c.user.id,action:'CREATE',entity:'CalendarEvent',entityId:e.id,summary:`Creó evento · ${e.title}`,request:req});return NextResponse.json(e,{status:201})}
export async function PATCH(req){const c=await context();if(!c||c.user.role!=='ADMIN')return NextResponse.json({error:'Solo administradores'},{status:403});const b=await req.json();const e=await prisma.calendarEvent.findFirst({where:{id:b.id,schoolId:c.user.schoolId}});if(!e)return NextResponse.json({error:'Evento no encontrado'},{status:404});const updated=await prisma.calendarEvent.update({where:{id:e.id},data:{active:b.active??e.active}});await writeAudit({schoolId:c.user.schoolId,actorId:c.user.id,action:'UPDATE',entity:'CalendarEvent',entityId:e.id,summary:`Actualizó evento · ${e.title}`,details:{active:updated.active},request:req});return NextResponse.json(updated)}
